prefix=/home/r/git/demo/FastFootShoes/data

rm -rf $prefix ; mkdir -vp $prefix
cd $prefix
mkdir -vp {server,locator}{1,2} derby

cd $prefix/derby ; $prefix/../demo/geode-server-package/startDerby.sh

cd $prefix/locator1 ; java -cp $(find $prefix/../FastFootShoesClusterSideLogic/target/ -name '*.jar' | xargs echo | sed 's/ /:/g') -Dlog4j.configurationFile=file:///home/r/git/demo/FastFootShoes/demo/geode-server-package/conf/log4j2.xml -Dgemfire.locators=u1[10334],u2[10335] -Dgemfire.enable-cluster-configuration=true -Dgemfire.load-cluster-configuration-from-dir=false -Dgemfire.log-level=config -Xms256m -Xmx256m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=15666 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Dgemfire.launcher.registerSignalHandlers=true -Djava.awt.headless=true  org.apache.geode.distributed.LocatorLauncher start locator1 --port=10334

cd $prefix/locator2 ; java -cp $(find $prefix/../FastFootShoesClusterSideLogic/target/ -name '*.jar'  | xargs echo | sed 's/ /:/g') -Dlog4j.configurationFile=file:///home/r/git/demo/FastFootShoes/demo/geode-server-package/conf/log4j2.xml -Dgemfire.locators=u1[10334],u2[10335] -Dgemfire.enable-cluster-configuration=true -Dgemfire.load-cluster-configuration-from-dir=false -Dgemfire.log-level=config -Xms256m -Xmx256m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=15667 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Dgemfire.launcher.registerSignalHandlers=true -Djava.awt.headless=true  org.apache.geode.distributed.LocatorLauncher start locator2 --port=10335

cd $prefix/server1 ; java -cp $(find $prefix/../FastFootShoesClusterSideLogic/target/ -name '*.jar'  | xargs echo | sed 's/ /:/g') -Dlog4j.configurationFile=file:///home/r/git/demo/FastFootShoes/demo/geode-server-package/conf/log4j2.xml -DgemfirePropertyFile=/home/r/git/demo/FastFootShoes/demo/geode-server-package/conf/gemfire.properties -Dgemfire.locators=u1[10334],u2[10335] -Dgemfire.start-dev-rest-api=false -Dgemfire.use-cluster-configuration=false -Dgemfire.log-level=config -Dgemfire.http-service-port=8181 -Dgemfire.start-dev-rest-api=true -Xms256m -Xmx256m -Dgemfire.launcher.registerSignalHandlers=true -Djava.awt.headless=true org.apache.geode.distributed.ServerLauncher start server1 --server-port=0 --spring-xml-location=file:///home/r/git/demo/FastFootShoes/demo/geode-server-package/conf/fastfootshoes-spring-cache.xml

cd $prefix/server2 ; java -cp $(find $prefix/../FastFootShoesClusterSideLogic/target/ -name '*.jar'  | xargs echo | sed 's/ /:/g') -Dlog4j.configurationFile=file:///home/r/git/demo/FastFootShoes/demo/geode-server-package/conf/log4j2.xml -DgemfirePropertyFile=/home/r/git/demo/FastFootShoes/demo/geode-server-package/conf/gemfire.properties -Dgemfire.locators=u1[10334],u2[10335] -Dgemfire.start-dev-rest-api=false -Dgemfire.use-cluster-configuration=false -Dgemfire.log-level=config -Dgemfire.http-service-port=8181 -Dgemfire.start-dev-rest-api=true -Xms256m -Xmx256m -Dgemfire.launcher.registerSignalHandlers=true -Djava.awt.headless=true org.apache.geode.distributed.ServerLauncher start server2 --server-port=0 --spring-xml-location=file:///home/r/git/demo/FastFootShoes/demo/geode-server-package/conf/fastfootshoes-spring-cache.xml

java -cp $(find $prefix/../FastFootShoesHistoricDataLoader/target/ -name '*.jar'  | xargs echo | sed 's/ /:/g') -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true FastFootShoesHistoricDataLoader.FastFootShoesHistoricDataLoaderApplication

java -cp $(find $prefix/../FastFootShoesRetailApp/target/ -name '*.jar'  | xargs echo | sed 's/ /:/g') -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true org.apache.geode.demo.fastfootshoes.application.Application
